// SPDX-FileCopyrightText: Copyright (c) Stanford University, The Regents of the
// University of California, and others. SPDX-License-Identifier: BSD-3-Clause

#include "active_stress_regazzoni.h"
#include "active_stress_test_helpers.h"
#include "gtest/gtest.h"

/**
 * @test Run a standalone RegazzoniActiveStress twitch for 600 updates with
 * @f$\Delta t=1\,\mathrm{ms}@f$ and the prescribed calcium and fiber-stretch
 * trajectories.
 *
 * The trusted reference is generated from the authors' @c cardiac-activation
 * C++ implementation at commit
 * @c 26f05df28891df7b3c69f16bb136cdced6b63c4d. The generator temporarily
 * zero-initializes six otherwise unassigned crossbridge-matrix entries, drives
 * the reference with the same calcium, sarcomere-length, and stretch-rate
 * inputs, and converts active tension from kPa to MPa. The values are not
 * generated by svMultiPhysics. See @ref RegazzoniActiveStress for the model
 * equations, numerical update, and state ordering.
 */
TEST(ActiveStressTrajectory, Regazzoni) {
  RegazzoniActiveStress::Parameters params;
  ActiveStressTrajectoryTest<RegazzoniActiveStress> trajectory(
      params, 600.0, 1.0, "active_stress_regazzoni_twitch.csv");
  trajectory.run();
}
