# This workflow checks that all .h/.cpp/.c files have the SPDX copyright header at the top
name: Copyright
on: [push, pull_request]
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check License
      uses: kt3k/license_checker@v3.3.1